CREATE TABLE Candidate(
            `CandidateID` INT NOT NULL AUTO_INCREMENT,
            `jobInterest` VARCHAR(64),
            `jobType` VARCHAR(64),
            `jobCV` VARCHAR(64),
            `transportation` VARCHAR(64),
            `LicenseNumber` VARCHAR(64),
            `classLicense` VARCHAR(64),
            `endorsement` VARCHAR(64) ,
            `citizenship` VARCHAR(64) ,
            `nationality` VARCHAR(64) ,
            `passportCountry` VARCHAR(64) ,
            `passportNumber` VARCHAR(64) ,
            `compensationInjury` VARCHAR(64) ,
            `compensationDateFrom` VARCHAR(64) ,
            `compensationDateTo` VARCHAR(64) ,
            `asthma` VARCHAR(2) ,
            `blackOut` VARCHAR(2) ,
            `diabetes` VARCHAR(2) ,
            `bronchitis` VARCHAR(2) ,
            `backInjury` VARCHAR(2) ,
            `deafness` VARCHAR(2) ,
            `dermatitis` VARCHAR(2) ,
            `skinInfection` VARCHAR(2) ,
            `allergies` VARCHAR(2) ,
            `hernia` VARCHAR(2) ,
            `highBloodPressure` VARCHAR(2) ,
            `heartProblems` VARCHAR(2) ,
            `usingDrugs` VARCHAR(2) ,
            `usingContactLenses` VARCHAR(2) ,
            `RSI` VARCHAR(2) ,
            `dependants` VARCHAR(2) ,
            `smoke` VARCHAR(2) ,
            `conviction` VARCHAR(2) ,
            `convictionDetails` VARCHAR(64),
            `UserID` int,
            `JobID` int,
            PRIMARY KEY(CandidateID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;